/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import type { Provider } from "@ethersproject/providers";
import type {
  HanaReceiver,
  HanaReceiverInterface,
} from "../../../../contracts/hevm/HanaConnectorHEVM.sol/HanaReceiver";

const _abi = [
  {
    inputs: [
      {
        components: [
          {
            internalType: "bytes",
            name: "hanaTxSenderAddress",
            type: "bytes",
          },
          {
            internalType: "uint256",
            name: "sourceChainId",
            type: "uint256",
          },
          {
            internalType: "address",
            name: "destinationAddress",
            type: "address",
          },
          {
            internalType: "uint256",
            name: "hanaValue",
            type: "uint256",
          },
          {
            internalType: "bytes",
            name: "message",
            type: "bytes",
          },
        ],
        internalType: "struct HanaInterfaces.HanaMessage",
        name: "hanaMessage",
        type: "tuple",
      },
    ],
    name: "onHanaMessage",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        components: [
          {
            internalType: "address",
            name: "hanaTxSenderAddress",
            type: "address",
          },
          {
            internalType: "uint256",
            name: "sourceChainId",
            type: "uint256",
          },
          {
            internalType: "bytes",
            name: "destinationAddress",
            type: "bytes",
          },
          {
            internalType: "uint256",
            name: "destinationChainId",
            type: "uint256",
          },
          {
            internalType: "uint256",
            name: "remainingHanaValue",
            type: "uint256",
          },
          {
            internalType: "bytes",
            name: "message",
            type: "bytes",
          },
        ],
        internalType: "struct HanaInterfaces.HanaRevert",
        name: "hanaRevert",
        type: "tuple",
      },
    ],
    name: "onHanaRevert",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
] as const;

export class HanaReceiver__factory {
  static readonly abi = _abi;
  static createInterface(): HanaReceiverInterface {
    return new utils.Interface(_abi) as HanaReceiverInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): HanaReceiver {
    return new Contract(address, _abi, signerOrProvider) as HanaReceiver;
  }
}
