/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import type { Provider } from "@ethersproject/providers";
import type {
  HanaCommonErrors,
  HanaCommonErrorsInterface,
} from "../../../../../contracts/evm/interfaces/HanaInterfaces.sol/HanaCommonErrors";

const _abi = [
  {
    inputs: [],
    name: "InvalidAddress",
    type: "error",
  },
] as const;

export class HanaCommonErrors__factory {
  static readonly abi = _abi;
  static createInterface(): HanaCommonErrorsInterface {
    return new utils.Interface(_abi) as HanaCommonErrorsInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): HanaCommonErrors {
    return new Contract(address, _abi, signerOrProvider) as HanaCommonErrors;
  }
}
