/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import type { Provider } from "@ethersproject/providers";
import type {
  HanaErrors,
  HanaErrorsInterface,
} from "../../../../contracts/evm/interfaces/HanaErrors";

const _abi = [
  {
    inputs: [
      {
        internalType: "address",
        name: "caller",
        type: "address",
      },
    ],
    name: "CallerIsNotConnector",
    type: "error",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "caller",
        type: "address",
      },
    ],
    name: "CallerIsNotTss",
    type: "error",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "caller",
        type: "address",
      },
    ],
    name: "CallerIsNotTssOrUpdater",
    type: "error",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "caller",
        type: "address",
      },
    ],
    name: "CallerIsNotTssUpdater",
    type: "error",
  },
  {
    inputs: [],
    name: "HanaTranserError",
    type: "error",
  },
  {
    inputs: [],
    name: "InvalidAddress",
    type: "error",
  },
] as const;

export class HanaErrors__factory {
  static readonly abi = _abi;
  static createInterface(): HanaErrorsInterface {
    return new utils.Interface(_abi) as HanaErrorsInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): HanaErrors {
    return new Contract(address, _abi, signerOrProvider) as HanaErrors;
  }
}
