/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumber,
  BigNumberish,
  BytesLike,
  CallOverrides,
  ContractTransaction,
  Overrides,
  PopulatedTransaction,
  Signer,
  utils,
} from "ethers";
import type {
  FunctionFragment,
  Result,
  EventFragment,
} from "@ethersproject/abi";
import type { Listener, Provider } from "@ethersproject/providers";
import type {
  TypedEventFilter,
  TypedEvent,
  TypedListener,
  OnEvent,
  PromiseOrValue,
} from "../../../../common";

export interface SystemContractMockInterface extends utils.Interface {
  functions: {
    "gasCoinHRC20ByChainId(uint256)": FunctionFragment;
    "gasHanaPoolByChainId(uint256)": FunctionFragment;
    "gasPriceByChainId(uint256)": FunctionFragment;
    "onCrossChainCall(address,address,uint256,bytes)": FunctionFragment;
    "setGasCoinHRC20(uint256,address)": FunctionFragment;
    "setGasPrice(uint256,uint256)": FunctionFragment;
    "setWHANAContractAddress(address)": FunctionFragment;
    "uniswapv2FactoryAddress()": FunctionFragment;
    "uniswapv2PairFor(address,address,address)": FunctionFragment;
    "uniswapv2Router02Address()": FunctionFragment;
    "wHanaContractAddress()": FunctionFragment;
  };

  getFunction(
    nameOrSignatureOrTopic:
      | "gasCoinHRC20ByChainId"
      | "gasHanaPoolByChainId"
      | "gasPriceByChainId"
      | "onCrossChainCall"
      | "setGasCoinHRC20"
      | "setGasPrice"
      | "setWHANAContractAddress"
      | "uniswapv2FactoryAddress"
      | "uniswapv2PairFor"
      | "uniswapv2Router02Address"
      | "wHanaContractAddress"
  ): FunctionFragment;

  encodeFunctionData(
    functionFragment: "gasCoinHRC20ByChainId",
    values: [PromiseOrValue<BigNumberish>]
  ): string;
  encodeFunctionData(
    functionFragment: "gasHanaPoolByChainId",
    values: [PromiseOrValue<BigNumberish>]
  ): string;
  encodeFunctionData(
    functionFragment: "gasPriceByChainId",
    values: [PromiseOrValue<BigNumberish>]
  ): string;
  encodeFunctionData(
    functionFragment: "onCrossChainCall",
    values: [
      PromiseOrValue<string>,
      PromiseOrValue<string>,
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<BytesLike>
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "setGasCoinHRC20",
    values: [PromiseOrValue<BigNumberish>, PromiseOrValue<string>]
  ): string;
  encodeFunctionData(
    functionFragment: "setGasPrice",
    values: [PromiseOrValue<BigNumberish>, PromiseOrValue<BigNumberish>]
  ): string;
  encodeFunctionData(
    functionFragment: "setWHANAContractAddress",
    values: [PromiseOrValue<string>]
  ): string;
  encodeFunctionData(
    functionFragment: "uniswapv2FactoryAddress",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "uniswapv2PairFor",
    values: [
      PromiseOrValue<string>,
      PromiseOrValue<string>,
      PromiseOrValue<string>
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "uniswapv2Router02Address",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "wHanaContractAddress",
    values?: undefined
  ): string;

  decodeFunctionResult(
    functionFragment: "gasCoinHRC20ByChainId",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "gasHanaPoolByChainId",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "gasPriceByChainId",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "onCrossChainCall",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setGasCoinHRC20",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setGasPrice",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setWHANAContractAddress",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "uniswapv2FactoryAddress",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "uniswapv2PairFor",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "uniswapv2Router02Address",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "wHanaContractAddress",
    data: BytesLike
  ): Result;

  events: {
    "SetGasCoin(uint256,address)": EventFragment;
    "SetGasHanaPool(uint256,address)": EventFragment;
    "SetGasPrice(uint256,uint256)": EventFragment;
    "SetWHana(address)": EventFragment;
    "SystemContractDeployed()": EventFragment;
  };

  getEvent(nameOrSignatureOrTopic: "SetGasCoin"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "SetGasHanaPool"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "SetGasPrice"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "SetWHana"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "SystemContractDeployed"): EventFragment;
}

export interface SetGasCoinEventObject {
  arg0: BigNumber;
  arg1: string;
}
export type SetGasCoinEvent = TypedEvent<
  [BigNumber, string],
  SetGasCoinEventObject
>;

export type SetGasCoinEventFilter = TypedEventFilter<SetGasCoinEvent>;

export interface SetGasHanaPoolEventObject {
  arg0: BigNumber;
  arg1: string;
}
export type SetGasHanaPoolEvent = TypedEvent<
  [BigNumber, string],
  SetGasHanaPoolEventObject
>;

export type SetGasHanaPoolEventFilter = TypedEventFilter<SetGasHanaPoolEvent>;

export interface SetGasPriceEventObject {
  arg0: BigNumber;
  arg1: BigNumber;
}
export type SetGasPriceEvent = TypedEvent<
  [BigNumber, BigNumber],
  SetGasPriceEventObject
>;

export type SetGasPriceEventFilter = TypedEventFilter<SetGasPriceEvent>;

export interface SetWHanaEventObject {
  arg0: string;
}
export type SetWHanaEvent = TypedEvent<[string], SetWHanaEventObject>;

export type SetWHanaEventFilter = TypedEventFilter<SetWHanaEvent>;

export interface SystemContractDeployedEventObject {}
export type SystemContractDeployedEvent = TypedEvent<
  [],
  SystemContractDeployedEventObject
>;

export type SystemContractDeployedEventFilter =
  TypedEventFilter<SystemContractDeployedEvent>;

export interface SystemContractMock extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  interface: SystemContractMockInterface;

  queryFilter<TEvent extends TypedEvent>(
    event: TypedEventFilter<TEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TEvent>>;

  listeners<TEvent extends TypedEvent>(
    eventFilter?: TypedEventFilter<TEvent>
  ): Array<TypedListener<TEvent>>;
  listeners(eventName?: string): Array<Listener>;
  removeAllListeners<TEvent extends TypedEvent>(
    eventFilter: TypedEventFilter<TEvent>
  ): this;
  removeAllListeners(eventName?: string): this;
  off: OnEvent<this>;
  on: OnEvent<this>;
  once: OnEvent<this>;
  removeListener: OnEvent<this>;

  functions: {
    gasCoinHRC20ByChainId(
      arg0: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<[string]>;

    gasHanaPoolByChainId(
      arg0: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<[string]>;

    gasPriceByChainId(
      arg0: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<[BigNumber]>;

    onCrossChainCall(
      target: PromiseOrValue<string>,
      hrc20: PromiseOrValue<string>,
      amount: PromiseOrValue<BigNumberish>,
      message: PromiseOrValue<BytesLike>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    setGasCoinHRC20(
      chainID: PromiseOrValue<BigNumberish>,
      hrc20: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    setGasPrice(
      chainID: PromiseOrValue<BigNumberish>,
      price: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    setWHANAContractAddress(
      addr: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    uniswapv2FactoryAddress(overrides?: CallOverrides): Promise<[string]>;

    uniswapv2PairFor(
      factory: PromiseOrValue<string>,
      tokenA: PromiseOrValue<string>,
      tokenB: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<[string] & { pair: string }>;

    uniswapv2Router02Address(overrides?: CallOverrides): Promise<[string]>;

    wHanaContractAddress(overrides?: CallOverrides): Promise<[string]>;
  };

  gasCoinHRC20ByChainId(
    arg0: PromiseOrValue<BigNumberish>,
    overrides?: CallOverrides
  ): Promise<string>;

  gasHanaPoolByChainId(
    arg0: PromiseOrValue<BigNumberish>,
    overrides?: CallOverrides
  ): Promise<string>;

  gasPriceByChainId(
    arg0: PromiseOrValue<BigNumberish>,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  onCrossChainCall(
    target: PromiseOrValue<string>,
    hrc20: PromiseOrValue<string>,
    amount: PromiseOrValue<BigNumberish>,
    message: PromiseOrValue<BytesLike>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  setGasCoinHRC20(
    chainID: PromiseOrValue<BigNumberish>,
    hrc20: PromiseOrValue<string>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  setGasPrice(
    chainID: PromiseOrValue<BigNumberish>,
    price: PromiseOrValue<BigNumberish>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  setWHANAContractAddress(
    addr: PromiseOrValue<string>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  uniswapv2FactoryAddress(overrides?: CallOverrides): Promise<string>;

  uniswapv2PairFor(
    factory: PromiseOrValue<string>,
    tokenA: PromiseOrValue<string>,
    tokenB: PromiseOrValue<string>,
    overrides?: CallOverrides
  ): Promise<string>;

  uniswapv2Router02Address(overrides?: CallOverrides): Promise<string>;

  wHanaContractAddress(overrides?: CallOverrides): Promise<string>;

  callStatic: {
    gasCoinHRC20ByChainId(
      arg0: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<string>;

    gasHanaPoolByChainId(
      arg0: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<string>;

    gasPriceByChainId(
      arg0: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    onCrossChainCall(
      target: PromiseOrValue<string>,
      hrc20: PromiseOrValue<string>,
      amount: PromiseOrValue<BigNumberish>,
      message: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<void>;

    setGasCoinHRC20(
      chainID: PromiseOrValue<BigNumberish>,
      hrc20: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<void>;

    setGasPrice(
      chainID: PromiseOrValue<BigNumberish>,
      price: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<void>;

    setWHANAContractAddress(
      addr: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<void>;

    uniswapv2FactoryAddress(overrides?: CallOverrides): Promise<string>;

    uniswapv2PairFor(
      factory: PromiseOrValue<string>,
      tokenA: PromiseOrValue<string>,
      tokenB: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<string>;

    uniswapv2Router02Address(overrides?: CallOverrides): Promise<string>;

    wHanaContractAddress(overrides?: CallOverrides): Promise<string>;
  };

  filters: {
    "SetGasCoin(uint256,address)"(
      arg0?: null,
      arg1?: null
    ): SetGasCoinEventFilter;
    SetGasCoin(arg0?: null, arg1?: null): SetGasCoinEventFilter;

    "SetGasHanaPool(uint256,address)"(
      arg0?: null,
      arg1?: null
    ): SetGasHanaPoolEventFilter;
    SetGasHanaPool(arg0?: null, arg1?: null): SetGasHanaPoolEventFilter;

    "SetGasPrice(uint256,uint256)"(
      arg0?: null,
      arg1?: null
    ): SetGasPriceEventFilter;
    SetGasPrice(arg0?: null, arg1?: null): SetGasPriceEventFilter;

    "SetWHana(address)"(arg0?: null): SetWHanaEventFilter;
    SetWHana(arg0?: null): SetWHanaEventFilter;

    "SystemContractDeployed()"(): SystemContractDeployedEventFilter;
    SystemContractDeployed(): SystemContractDeployedEventFilter;
  };

  estimateGas: {
    gasCoinHRC20ByChainId(
      arg0: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    gasHanaPoolByChainId(
      arg0: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    gasPriceByChainId(
      arg0: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    onCrossChainCall(
      target: PromiseOrValue<string>,
      hrc20: PromiseOrValue<string>,
      amount: PromiseOrValue<BigNumberish>,
      message: PromiseOrValue<BytesLike>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    setGasCoinHRC20(
      chainID: PromiseOrValue<BigNumberish>,
      hrc20: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    setGasPrice(
      chainID: PromiseOrValue<BigNumberish>,
      price: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    setWHANAContractAddress(
      addr: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    uniswapv2FactoryAddress(overrides?: CallOverrides): Promise<BigNumber>;

    uniswapv2PairFor(
      factory: PromiseOrValue<string>,
      tokenA: PromiseOrValue<string>,
      tokenB: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    uniswapv2Router02Address(overrides?: CallOverrides): Promise<BigNumber>;

    wHanaContractAddress(overrides?: CallOverrides): Promise<BigNumber>;
  };

  populateTransaction: {
    gasCoinHRC20ByChainId(
      arg0: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    gasHanaPoolByChainId(
      arg0: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    gasPriceByChainId(
      arg0: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    onCrossChainCall(
      target: PromiseOrValue<string>,
      hrc20: PromiseOrValue<string>,
      amount: PromiseOrValue<BigNumberish>,
      message: PromiseOrValue<BytesLike>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    setGasCoinHRC20(
      chainID: PromiseOrValue<BigNumberish>,
      hrc20: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    setGasPrice(
      chainID: PromiseOrValue<BigNumberish>,
      price: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    setWHANAContractAddress(
      addr: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    uniswapv2FactoryAddress(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    uniswapv2PairFor(
      factory: PromiseOrValue<string>,
      tokenA: PromiseOrValue<string>,
      tokenB: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    uniswapv2Router02Address(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    wHanaContractAddress(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;
  };
}
