/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { HanaConnectorHEVM } from "./HanaConnectorHEVM";
export type { HanaReceiver } from "./HanaReceiver";
