/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import type { Provider } from "@ethersproject/providers";
import type {
  HanaTokenConsumerUniV3Errors,
  HanaTokenConsumerUniV3ErrorsInterface,
} from "../../../../../contracts/evm/tools/HanaTokenConsumerUniV3.strategy.sol/HanaTokenConsumerUniV3Errors";

const _abi = [
  {
    inputs: [],
    name: "ErrorSendingETH",
    type: "error",
  },
  {
    inputs: [],
    name: "InputCantBeZero",
    type: "error",
  },
  {
    inputs: [],
    name: "ReentrancyError",
    type: "error",
  },
] as const;

export class HanaTokenConsumerUniV3Errors__factory {
  static readonly abi = _abi;
  static createInterface(): HanaTokenConsumerUniV3ErrorsInterface {
    return new utils.Interface(_abi) as HanaTokenConsumerUniV3ErrorsInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): HanaTokenConsumerUniV3Errors {
    return new Contract(
      address,
      _abi,
      signerOrProvider
    ) as HanaTokenConsumerUniV3Errors;
  }
}
