/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import type { Provider } from "@ethersproject/providers";
import type {
  WHANA,
  WHANAInterface,
} from "../../../../contracts/hevm/ConnectorHEVM.sol/WHANA";

const _abi = [
  {
    inputs: [
      {
        internalType: "address",
        name: "src",
        type: "address",
      },
      {
        internalType: "address",
        name: "dst",
        type: "address",
      },
      {
        internalType: "uint256",
        name: "wad",
        type: "uint256",
      },
    ],
    name: "transferFrom",
    outputs: [
      {
        internalType: "bool",
        name: "",
        type: "bool",
      },
    ],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "uint256",
        name: "wad",
        type: "uint256",
      },
    ],
    name: "withdraw",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
] as const;

export class WHANA__factory {
  static readonly abi = _abi;
  static createInterface(): WHANAInterface {
    return new utils.Interface(_abi) as WHANAInterface;
  }
  static connect(address: string, signerOrProvider: Signer | Provider): WHANA {
    return new Contract(address, _abi, signerOrProvider) as WHANA;
  }
}
