/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { IHRC20 } from "./IHRC20";
export type { IHRC20Metadata } from "./IHRC20Metadata";
export type { ISystem } from "./ISystem";
