/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { HRC20__factory } from "./HRC20__factory";
export { HRC20Errors__factory } from "./HRC20Errors__factory";
