/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as connectorHevmSol from "./ConnectorHEVM.sol";
export type { connectorHevmSol };
import type * as hrc20Sol from "./HRC20.sol";
export type { hrc20Sol };
import type * as interfacesSol from "./Interfaces.sol";
export type { interfacesSol };
import type * as systemContractSol from "./SystemContract.sol";
export type { systemContractSol };
import type * as wzetaSol from "./WZETA.sol";
export type { wzetaSol };
import type * as interfaces from "./interfaces";
export type { interfaces };
