/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as hrc20Sol from "./HRC20.sol";
export type { hrc20Sol };
import type * as hanaConnectorHevmSol from "./HanaConnectorHEVM.sol";
export type { hanaConnectorHevmSol };
import type * as interfacesSol from "./Interfaces.sol";
export type { interfacesSol };
import type * as systemContractSol from "./SystemContract.sol";
export type { systemContractSol };
import type * as whanaSol from "./WHANA.sol";
export type { whanaSol };
import type * as interfaces from "./interfaces";
export type { interfaces };
import type * as testing from "./testing";
export type { testing };
