name: Create Pull Request for Upstream Changes

on:
  schedule:
    - cron: '0 0 * * *'

permissions: write-all

jobs:
  sync_latest_from_upstream:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set branch name
        run: echo "BRANCH_NAME=update-upstream-$(date +%Y-%m-%d)" >> $GITHUB_ENV

      - name: Setup Git
        run: |
          git config user.name 'github-actions[bot]'
          git config user.email 'github-actions[bot]@users.noreply.github.com'

      - name: Add upstream remote
        run: git remote add upstream https://github.com/zeta-chain/protocol-contracts

      - name: Fetch upstream changes
        run: git fetch upstream

      - name: Checkout a new branch for upstream changes
        run: |
          git checkout -b ${{ env.BRANCH_NAME }}

      - name: Merge upstream changes
        run: git merge upstream/main --no-commit --no-ff

      - name: Commit changes
        run: |
          git commit -m "Merge upstream changes"
          git push origin HEAD

  create-pull-request:
    runs-on: ubuntu-latest
    needs: sync_latest_from_upstream

    steps:
      - name: Set branch name
        run: echo "BRANCH_NAME=update-upstream-$(date +%Y-%m-%d)" >> $GITHUB_ENV

      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          ref:  ${{ env.BRANCH_NAME }}

      - name: Authenticate with GitHub
        run: |
          echo "${{ secrets.GITHUB_TOKEN }}" | gh auth login --with-token

      - name: Create Pull Request
        run: |
          gh pr create --title "Automatic Pull Request" --body "This is an automatically created pull request." --base main