/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import type { Provider } from "@ethersproject/providers";
import type {
  HanaTokenConsumerUniV2Errors,
  HanaTokenConsumerUniV2ErrorsInterface,
} from "../../../../../contracts/evm/tools/HanaTokenConsumerUniV2.strategy.sol/HanaTokenConsumerUniV2Errors";

const _abi = [
  {
    inputs: [],
    name: "InputCantBeZero",
    type: "error",
  },
] as const;

export class HanaTokenConsumerUniV2Errors__factory {
  static readonly abi = _abi;
  static createInterface(): HanaTokenConsumerUniV2ErrorsInterface {
    return new utils.Interface(_abi) as HanaTokenConsumerUniV2ErrorsInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): HanaTokenConsumerUniV2Errors {
    return new Contract(
      address,
      _abi,
      signerOrProvider
    ) as HanaTokenConsumerUniV2Errors;
  }
}
